name: en-net daily update

on:
  schedule:
  - cron: "5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Extract en-net discussions for the day
        run: Rscript ennet_db.R
