name: ennet_hourly_update

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  ennet-daily-updates:
    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        r-version: [4.0.3]

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}
          
      - name: Install system dependencies
        run: sudo apt install libcurl4-openssl-dev
          
      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_github("katilingban/ennet")
        shell: Rscript {0}

      - name: Extract topics and discussions
        run: Rscript ennet_topics.R

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "extract new ennet topics" -a
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "main"
